### ISSUE TITLE
README.md with duplicated text

### ISSUE THREAD

**Issue by Ikaro0** [rubenmromero/ssh-tunneling#1]
Hi Rubén, 
Nice tutorial but it looks like it has a mistype on README.md at "Publishing local services through reverse SSH tunnels in gateway mode" cause the text is the same as on "Tunnels as daemons!"

Regards

**Comment by rubenmromero** [comment]
Hello Ikaro,

Thanks a lot for your comment, I appreciate it so much! And you are right, the paragraph was duplicated by mistake, but it is already fixed with the proper text.

Thanks again for warning me and I hope that now everything is ok.

Kind regards!
